### ISSUE TITLE
how to use and show result? please

### ISSUE THREAD

**Issue by cenchaojun** [ZhenglinZhou/Data-Augmentation-Zoo-for-Object-Detection#1]
i just want to save augment image. how? please~

**Comment by dreamitpossible1** [comment]
0
1
2
3
4
5
6
7
8
Traceback (most recent call last):
  File "D:/360极速浏览器下载/Data_Augmentation_Zoo_for_Object_Detection-master/Data_Augmentation_Zoo_for_Object_Detection-master/test_augmentation.py", line 32, in <module>
    sample = voc_train[i]
  File "D:\360极速浏览器下载\Data_Augmentation_Zoo_for_Object_Detection-master\Data_Augmentation_Zoo_for_Object_Detection-master\prepare_data.py", line 147, in __getitem__
    img = self.load_image(image_index)
  File "D:\360极速浏览器下载\Data_Augmentation_Zoo_for_Object_Detection-master\Data_Augmentation_Zoo_for_Object_Detection-master\prepare_data.py", line 167, in load_image
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-q3d_8t8e\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by dinhanhx** [comment]
@dreamitpossible1 Can you just not spam your error log? It doesn't make any sense with the current context of this issue.
